ADDED: services/micro/c example
ConnectEverything/nats-by-example pull request #198
Opened 2024-05-14 20:09 UTC by levb

2024-05-14 20:09 UTC, levb commented on docker/c/Dockerfile
> +COPY CMakeLists.txt .
Will be used to build all C examples

2024-05-14 22:56 UTC, mtmk approved these changes
LGTM

2024-05-15 06:03 UTC, Jarema requested changes
Looks ok, and generates the output.

Would be nice to add headers like in Go example:

https://nats-by-example-wfyr11i7s-connecteverything.vercel.app/examples/services/intro/go

2024-05-15 15:29 UTC, levb commented
@Jarema I can add headers, but... I don't see headers used in the Go example either. Am I missing something?

2024-05-15 15:32 UTC, Jarema commented
@levb sorry, I meant headlines - "Defining a service", "Adding endoints"

2024-05-15 15:35 UTC, levb commented
@Jarema Ah! I deliberately removed them since the code vs. the config data are kind of scattered in the C code, no inlines.

2024-06-04 12:55 UTC, Jarema approved these changes
LGTM!

2024-06-04 12:58 UTC, merged