[Java] Concurrent Message Processing
ConnectEverything/nats-by-example pull request #255
Opened 2024-08-08 07:42 UTC by MauriceVanVeen

Resolves https://github.com/ConnectEverything/nats-by-example/issues/247

Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/248

2024-08-08 15:11 UTC, scottf requested changes
I think the intention of this was to show queue subscribing that got messages in parallel (concurrent). We might need to look at the other examples and fix them

2024-08-08 15:11 UTC, scottf commented on examples/messaging/concurrent/java/Main.java
> +                .useDispatcherWithExecutor()
Don't use this.

2024-08-08 15:32 UTC, MauriceVanVeen commented
@scottf, the description on NBE does mention queue groups, but it then goes on to say:

> However, even within a subscription, it may be desirable to handle messages concurrently. This example shows how this can be achieved in the clients that support it.

Apart from queue groups and the dispatcher with executor, not sure if the Java client supports another way for concurrent processing?

2024-08-08 16:12 UTC, scottf commented
> Apart from queue groups and the dispatcher with executor, not sure if the Java client supports another way for concurrent processing?

I think queue group and dispatchers is the way to go for this example

2024-08-09 07:39 UTC, MauriceVanVeen commented
Have updated it to use dispatchers+queue groups now.

2024-08-09 19:44 UTC, merged